# Generated by Django 4.0.5 on 2022-06-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userbase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
